services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs,s3,dynamodb
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4571:4571"

  replay:
    build: .
    container_name: intention-com-web
    entrypoint: ["npm", "run", "replay"]
    environment:
      BUCKET_NAME: intention-com-web-bucket-local
      OBJECT_PREFIX: events/
      REPLAY_QUEUE_URL: http://sqs.eu-west-2.localhost.localstack.cloud:4566/000000000000/xn--intenton-z2a-replay-queue-local
      AWS_REGION: eu-west-2
      AWS_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: LKIAQAAAAAAVNCBMPNSG
      AWS_SECRET_ACCESS_KEY: localstack
    depends_on:
      - localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
